
```{r}
library(data.table)
library(tidyverse)
library(ade4)       # dudi.pca, s.class
```


```{r}
get_data <- function(data = iris, slice_n = NULL) {
  if (!is.null(slice_n)) {
    return(data[slice_n, ])
  } else {
    return(data)
  }
}


calculate_anova_model <- function(data_ = iris) {
  r <- aov(lm(data_[, 1] ~ ., data = data_[-1]))
  return(summary(r))
}


calculate_PCA_model <- function(data_) {
  pca_res <- data_ %>%
    as.data.table() %>%
    copy() %>% 
    .[, scale(.SD), .SDcols = is.numeric] %>% 
    princomp()
  return(pca_res)
}

plot_pairs <- \(data_, file_name = "pairs_plot") {
  pdf(paste0("02.Outputs/", file_name, ".pdf"))
  data_ %>% pairs()
  dev.off()
  return(invisible(NULL))
}

pca_plot_lesser_dim <- function(data_, factor_var, file_name = "PCA_less_dim") {
  pca_res <- data_ %>%
    as.data.table() %>%
    copy() %>% 
    .[, scale(.SD), .SDcols = is.numeric] %>% 
    ade4::dudi.pca(scannf=FALSE)
  
  pdf(paste0("02.Outputs/", file_name, ".pdf"))
  ade4::s.class(pca_res$li, data_[, factor_var])
  dev.off()
  
  return(invisible(NULL))
}
```

```{r}
pca_summary <- \(pca_res) pca_res %>% summary()
pca_loadings <- \(pca_res) pca_res %>% loadings()

plot_to_pdf <- function(pca_res, file_name = "my_plot") {
  pdf(paste0("02.Outputs/", file_name, ".pdf"))
  pca_res %>% plot()
  dev.off()
  return(invisible(NULL))
}
```

```{r}
get_data() %>%
  pca_plot_lesser_dim("Species")

get_data() %>% 
  calculate_PCA_model() %>% 
  pca_plot()
```

